### ISSUE TITLE
latestTestVersion won't be respected if it is less than the current minimum version.

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/version-check-swift#8]
I believe latestTestVersion is meant to allow developers/testers to use older versions of the app than is allowed with app store, but the current logic prevents it from ever working.

Lets assume: 
- Testing on version 1.1
- Current app store release is 1.3
- Minimum version is 1.2

Since blockedVersions is checked before latestTestVersion, and we're working on a build before the minimum version, we'll get the blocked version message and be forced to upgrade.

@nbrooke am I misunderstanding the latestTestVersion check or this a bug?

**Comment by nbrooke** [comment]
That's NOT the intended purpose of latestTestVersion (though what you describe is a feature that might be useful). 

The idea there is to provide a way for beta versions to get a "there is a newer beta release out" notification (not as hard as a forced upgrade, you can click though it, but at least then clients / beta testers are less likely to keep running an old version). So the intended set up would be something more like:

Minimum version is 1.0
App store release is 1.1
Current ad hoc beta build is 1.2
latestTestVersion is 1.2

Any one with an ad hoc build of 1.1 or earlier would get a warning about having an out of date test version, until they either went to the app store 1.1 or got the latest 1.2 beta version. Note that this does require that test builds are #ifdef'd to set `isTestBuild` to true when creating the `DefaultUpdateDisplay` or handling the `suggestUpdate` event yourself if you aren't using that.

**Comment by nbrooke** [comment]
Added #10 and #11 with based on other discussions it sounds like are more the features that we actually want to address the potential use cases here, so closing this.
